name: dep-compose
channels:
  - pytorch
  - nvidia
dependencies:
  - pytorch-cuda=11.8
  - pytorch
  - torchvision
  - torchaudio
  - transformers
  - gensim
  - pip
  - pip:
    - git+https://github.com/peterr-s/conllu.git@tree-to-list
